title: "Youwei Liu | Academic Homepage"
description: "Personal academic homepage of Youwei Liu."
url: "https://loyiv.github.io"
baseurl: ""
repository: "loyiv/loyiv.github.io"
timezone: Asia/Shanghai

# Build settings
markdown: kramdown
plugins:
  - jekyll-email-protect

exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules

collections:
  - publications
  - news
